[project]
name = "tacc-portal-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.139.0",
    "ipython>=9.15.0",
    "jupyterlab>=4.6.1",
    "litellm>=1.92.0",
    "openai>=2.45.0",
    "pydantic-ai-litellm>=0.2.8",
    "pydantic-ai-slim[ag-ui]>=2.9.1",
    "pydantic-settings>=2.14.2",
    "pyjwt[crypto]>=2.13.0",
    "supervisor>=4.3.0",
    "tapipy>=25.4.0",
    "uvicorn>=0.51.0",
]
